package server

import (
	"net/http"

	"payment-gateway/internal/mcp"
)

func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()
	mcp.New(s.db, s.cfg, s.workers.PriceWorker, s.agents, s.webhooks).RegisterRoutes(mux, func(w http.ResponseWriter, r *http.Request) bool {
		_, ok := s.authorizeChainFX(w, r)
		return ok
	})
	mux.HandleFunc("GET /", s.handleDevelopers)
	mux.HandleFunc("GET /admin", s.handleWebAvailability)
	mux.HandleFunc("GET /developers", s.handleDevelopers)
	mux.HandleFunc("GET /developers/dashboard", s.handleDevelopersDashboard)
	mux.HandleFunc("GET /developers/dashboard.json", s.handleDevelopersDashboard)
	mux.HandleFunc("GET /developers/api-keys", s.handleDeveloperAPIKeys)
	mux.HandleFunc("GET /developers/logs", s.handleDeveloperLogs)
	mux.HandleFunc("GET /app/agent/", s.handleWebAvailability)
	mux.HandleFunc("GET /app/agent/summary", s.handleAgentConsoleSummary)
	mux.HandleFunc("GET /app/agent/{id}", s.handleAppAgentDetail)
	mux.HandleFunc("GET /app/purchase/{id}", s.handleAppPurchaseDetail)
	mux.HandleFunc("GET /app/execution/{id}", s.handleAppExecutionDetail)
	mux.HandleFunc("GET /app/fees", s.handleAppFees)
	mux.HandleFunc("GET /app/webhooks", s.handleAppWebhooksUI)
	mux.HandleFunc("GET /mcp/test", s.handleMCPTestConnection)
	mux.HandleFunc("GET /app/developer/", s.handleWebAvailability)
	mux.HandleFunc("GET /app/developer/summary", s.handleDeveloperConsoleSummary)
	mux.HandleFunc("GET /developer/projects", s.handleListDeveloperProjects)
	mux.HandleFunc("POST /developer/projects", s.handleCreateDeveloperProject)
	mux.HandleFunc("GET /developer/projects/{id}", s.handleGetDeveloperProject)
	mux.HandleFunc("PATCH /developer/projects/{id}", s.handleUpdateDeveloperProject)
	mux.HandleFunc("GET /developer/api-keys", s.handleListDeveloperAPIKeysV2)
	mux.HandleFunc("POST /developer/projects/{id}/api-keys", s.handleCreateDeveloperProjectAPIKey)
	mux.HandleFunc("POST /developer/api-keys/{id}/rotate", s.handleRotateDeveloperAPIKey)
	mux.HandleFunc("POST /developer/api-keys/{id}/{status}", s.handleSetDeveloperAPIKeyStatus)
	mux.HandleFunc("POST /api/admin/login", s.handleAdminLogin)
	mux.HandleFunc("GET /api/admin/overview", s.handleAdminOverview)
	mux.HandleFunc("GET /api/admin/transactions", s.handleAdminTransactions)
	mux.HandleFunc("POST /api/admin/signer/probe", s.handleAdminSignerProbe)
	mux.HandleFunc("POST /api/admin/mobile-test/purge", s.handleAdminMobileTestPurge)
	mux.HandleFunc("POST /api/agents/market-analysis", s.handleAgentMarketAnalysis)
	mux.HandleFunc("POST /api/agents/recommend", s.handleAgentRecommend)
	mux.HandleFunc("POST /api/agents/anomalies", s.handleAgentAnomalies)
	mux.HandleFunc("POST /api/agents/predict", s.handleAgentPredict)
	mux.HandleFunc("POST /api/agents/summary", s.handleAgentSummary)
	mux.HandleFunc("GET /api/webhooks/events", s.handleListWebhookEvents)
	mux.HandleFunc("POST /api/webhooks/subscriptions", s.handleCreateWebhookSubscription)
	mux.HandleFunc("GET /api/webhooks/subscriptions", s.handleListWebhookSubscriptions)
	mux.HandleFunc("DELETE /api/webhooks/subscriptions/{id}", s.handleDeleteWebhookSubscription)
	mux.HandleFunc("POST /api/webhooks/subscriptions/{id}/active", s.handleSetWebhookSubscriptionActive)
	mux.HandleFunc("POST /api/webhooks/subscriptions/{id}/test", s.handleTestWebhookSubscription)
	mux.HandleFunc("GET /api/webhooks/subscriptions/{id}/logs", s.handleWebhookSubscriptionLogs)
	mux.HandleFunc("GET /api/webhooks/dashboard", s.handleWebhookDashboard)
	mux.HandleFunc("GET /.well-known/ai-services.json", s.handleAIServicesWellKnown)
	mux.HandleFunc("GET /.well-known/agent-card.json", s.handleA2AAgentCard)
	mux.HandleFunc("GET /.well-known/agent.json", s.handleA2AAgentCard)
	mux.HandleFunc("GET /.well-known/jwks.json", s.handleAgentJWKS)
	mux.HandleFunc("GET /.well-known/agent-card.signature", s.handleAgentCardSignature)
	mux.HandleFunc("GET /.well-known/agent-reputation.json", s.handleAgentReputationWellKnown)
	mux.HandleFunc("GET /.well-known/agent-sla.json", s.handleAgentSLAWellKnown)
	mux.HandleFunc("GET /.well-known/agntcy.json", s.handleAGNTCYWellKnown)
	mux.HandleFunc("GET /.well-known/oasf.json", s.handleOASFWellKnown)
	mux.HandleFunc("GET /.well-known/x402.json", s.handleX402WellKnown)
	mux.HandleFunc("GET /agent-pay.json", s.handleAgentPayOnboarding)
	mux.HandleFunc("POST /a2a", s.handleA2A)
	mux.HandleFunc("POST /a2a/tasks", s.handleA2ATaskCreate)
	mux.HandleFunc("GET /a2a/tasks/{id}", s.handleA2ATaskGet)
	mux.HandleFunc("GET /a2a/tasks/{id}/events", s.handleA2ATaskEvents)
	mux.HandleFunc("GET /llms.txt", s.handleLLMSTxt)
	mux.HandleFunc("GET /robots.txt", s.handleRobotsTxt)
	mux.HandleFunc("GET /sitemap.xml", s.handleSitemap)
	mux.HandleFunc("GET /marketplace/apis", s.handleMarketplaceAPIs)
	mux.HandleFunc("GET /marketplace/apis/{id}", s.handleMarketplaceAPI)
	mux.HandleFunc("GET /marketplace/capabilities", s.handleMarketplaceCapabilities)
	mux.HandleFunc("GET /marketplace/capabilities/{id}", s.handleMarketplaceCapability)
	mux.HandleFunc("GET /marketplace/capabilities/{id}/contract", s.handleMarketplaceCapabilityContract)
	mux.HandleFunc("POST /marketplace/capabilities/{id}/purchase", s.handleMarketplaceCapabilityPurchase)
	mux.HandleFunc("POST /marketplace/capabilities/{id}/usage", s.handleMarketplaceCapabilityUsage)
	mux.HandleFunc("GET /marketplace/products", s.handleMarketplaceProducts)
	mux.HandleFunc("GET /marketplace/products/{id}", s.handleMarketplaceProduct)
	mux.HandleFunc("POST /marketplace/purchase", s.handleMarketplacePurchaseCreate)
	mux.HandleFunc("GET /marketplace/purchase/{id}", s.handleMarketplacePurchaseGet)
	mux.HandleFunc("POST /marketplace/purchase/{id}/execute", s.handleMarketplacePurchaseExecute)
	mux.HandleFunc("POST /marketplace/usage", s.handleMarketplaceUsage)
	mux.HandleFunc("POST /v1/access/quote", s.handleAccessQuote)
	mux.HandleFunc("POST /v1/access/purchase", s.handleAccessPurchase)
	mux.HandleFunc("GET /v1/access/{id}", s.handleAccessGet)
	mux.HandleFunc("POST /v1/meter/usage", s.handleMeterUsage)
	mux.HandleFunc("POST /x402/capabilities/{capability}/execute", s.handleX402CapabilityExecute)
	mux.HandleFunc("GET /agent/v1/capabilities", s.handleAgentCapabilities)
	mux.HandleFunc("GET /agent/v1/reputation", s.handleAgentReputation)
	mux.HandleFunc("GET /agent/v1/sla", s.handleAgentSLA)
	mux.HandleFunc("GET /agent/v1/episodes", s.handleAgentEpisodes)
	mux.HandleFunc("GET /agent/v1/episodes/{id}", s.handleAgentEpisode)
	mux.HandleFunc("GET /agent/v1/registries", s.handleAgentRegistries)
	mux.HandleFunc("GET /agent/v1/registry-records/{id}", s.handleAgentRegistryRecord)
	mux.HandleFunc("GET /agent/v1/eips", s.handleAgentEIPCapabilities)
	mux.HandleFunc("POST /agent/v1/eips/prepare", s.handleAgentEIPPrepare)
	mux.HandleFunc("POST /agent/v1/eips/verify", s.handleAgentEIPVerify)
	mux.HandleFunc("GET /agent/v1/eips/test-suite", s.handleAgentEIPTestSuiteStatus)
	mux.HandleFunc("POST /agent/v1/eips/test-suite", s.handleAgentEIPTestSuiteRun)
	mux.HandleFunc("POST /agent/connect", s.handleAgentConnect)
	mux.HandleFunc("GET /agent/{id}/policy", s.handleGetAgentPolicy)
	mux.HandleFunc("PATCH /agent/{id}/policy", s.handleUpdateAgentPolicy)
	mux.HandleFunc("GET /agent/v1/capabilities/{capability}/contract", s.handleAgentCapabilityContract)
	mux.HandleFunc("POST /agent/v1/capabilities/{capability}/route", s.handleAgentCapabilityRoute)
	mux.HandleFunc("POST /agent/v1/capabilities/{capability}/execute", s.handleAgentCapabilityExecute)
	mux.HandleFunc("GET /agent/v1/assets", s.handleAgentAssets)
	mux.HandleFunc("POST /agent/v1/trade/quote", s.handleAgentTradeQuote)
	mux.HandleFunc("POST /agent/v1/trade/execute", s.handleAgentTradeExecute)
	mux.HandleFunc("GET /agent/v1/trade/{id}", s.handleAgentTradeGet)
	// M2M agent payments: PIX + credit-card on behalf of AI agents
	mux.HandleFunc("POST /agent/v1/pay", s.handleM2MCreateIntent)
	mux.HandleFunc("GET /agent/v1/pay/{id}", s.handleM2MGetIntent)
	// Agent pricing policy (per-agent fee overrides)
	mux.HandleFunc("GET /agent/v1/pricing/{wallet}", s.handleGetAgentPricingPolicy)
	// Detail pages
	mux.HandleFunc("GET /app/intent/{id}", s.handleAppIntentDetail)
	// Risk / settlement operational dashboard
	mux.HandleFunc("GET /app/risk", s.handleAppRisk)
	// Public MCP capability registry (machine-readable JSON)
	mux.HandleFunc("GET /mcp/capabilities.json", s.handleMCPCapabilityRegistry)
	mux.HandleFunc("GET /openapi.json", s.handleOpenAPI)
	mux.HandleFunc("GET /rates", s.handleChainFXRates)
	mux.HandleFunc("GET /api/rates", s.handleChainFXRates)
	mux.HandleFunc("POST /quote", s.handleChainFXQuote)
	mux.HandleFunc("POST /buy", s.handleChainFXBuy)
	mux.HandleFunc("POST /sell", s.handleChainFXSell)
	mux.HandleFunc("GET /order/{id}", s.handleChainFXOrder)
	mux.HandleFunc("POST /webhooks/test", s.handleChainFXWebhookTest)
	mux.HandleFunc("POST /webhooks/retry", s.handleChainFXWebhookRetry)
	mux.HandleFunc("GET /api/price", s.handlePrice)
	mux.HandleFunc("GET /api/quote", s.handleQuote)
	mux.HandleFunc("POST /api/quote", s.handleQuote)
	mux.HandleFunc("POST /api/buy", s.handleCreateBuy)
	mux.HandleFunc("GET /api/buy/{id}", s.handleGetBuy)
	mux.HandleFunc("GET /api/buy/{id}/stream", s.handleBuyStream)
	mux.HandleFunc("POST /api/order", s.handleCreateOrder)
	mux.HandleFunc("GET /api/order/{id}", s.handleGetOrder)
	mux.HandleFunc("GET /api/order/{id}/stream", s.handleOrderStream)
	mux.HandleFunc("POST /api/order/{id}/deposit", s.handleDeposit)
	mux.HandleFunc("POST /api/order/{id}/payout", s.handlePayout)
	mux.HandleFunc("POST /api/pix/webhook", s.handlePixWebhook)
	mux.HandleFunc("POST /api/pix/webhook/buy", s.handlePixWebhookBuy)
	mux.HandleFunc("POST /api/efi/charges/webhook/buy", s.handleEfiChargesWebhookBuy)
	mux.HandleFunc("POST /internal/sweep", s.handleInternalSweep)
	mux.HandleFunc("POST /internal/m2m/settled", s.handleInternalM2MSettled)
	mux.HandleFunc("POST /internal/email/test", s.handleEmailTest)
	mux.HandleFunc("POST /internal/email/marketing", s.handleMarketingEmail)
	// ── Gas Station (Paymaster) ───────────────────────────────────────────────
	mux.HandleFunc("GET /v1/gas/status", s.handleGasStatus)
	mux.HandleFunc("POST /v1/gas/quote", s.handleGasQuote)
	mux.HandleFunc("POST /v1/gas/relay", s.handleGasRelay)
	mux.HandleFunc("GET /v1/gas/relay/{id}", s.handleGasRelayGet)
	mux.HandleFunc("GET /api/admin/gas-station", s.handleAdminGasStation)
	mux.HandleFunc("GET /api/admin/sweeper", s.handleAdminSweeper)
	// ── Chaos / Adversarial Admin ─────────────────────────────────────────────
	mux.HandleFunc("POST /v1/admin/gas/chaos-run", s.handleTriggerChaos)
	mux.HandleFunc("GET /v1/admin/gas/chaos-history", s.handleChaosHistory)
	mux.HandleFunc("GET /admin/chaos", s.handleAdminChaosPage)
	// ─────────────────────────────────────────────────────────────────────────
	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, _ *http.Request) { writeJSON(w, http.StatusOK, map[string]any{"ok": true}) })
	mux.HandleFunc("GET /readyz", s.handleReady)
	// Prometheus-compatible metrics endpoint — protected by admin bearer auth.
	mux.HandleFunc("GET /metrics", s.handleMetrics)
	return securityHeaders(cors(s.cfg, withRequestID(s.withServerTiming(s.withDeveloperRequestLog(s.withPublicSurfaceGuards(s.withSmartRateLimit(mux)))))))
}
