package server

import (
	"net/http"

	"payment-gateway/internal/mcp"
)

func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()
	mcp.New(s.db, s.cfg, s.workers.PriceWorker, s.agents, s.webhooks).RegisterRoutes(mux, func(w http.ResponseWriter, r *http.Request) bool {
		_, ok := s.authorizeChainFX(w, r)
		return ok
	})
	mux.HandleFunc("GET /developers", s.handleDevelopers)
	mux.HandleFunc("GET /developers/dashboard", s.handleDevelopersDashboard)
	mux.HandleFunc("GET /developers/dashboard.json", s.handleDevelopersDashboard)
	mux.HandleFunc("GET /developers/api-keys", s.handleDeveloperAPIKeys)
	mux.HandleFunc("GET /developers/logs", s.handleDeveloperLogs)
	mux.HandleFunc("GET /app/agent/summary", s.handleAgentConsoleSummary)
	mux.HandleFunc("GET /app/developer/summary", s.handleDeveloperConsoleSummary)
	mux.HandleFunc("POST /api/admin/login", s.handleAdminLogin)
	mux.HandleFunc("GET /api/admin/overview", s.handleAdminOverview)
	mux.HandleFunc("GET /api/admin/transactions", s.handleAdminTransactions)
	mux.HandleFunc("POST /api/agents/market-analysis", s.handleAgentMarketAnalysis)
	mux.HandleFunc("POST /api/agents/recommend", s.handleAgentRecommend)
	mux.HandleFunc("POST /api/agents/anomalies", s.handleAgentAnomalies)
	mux.HandleFunc("POST /api/agents/predict", s.handleAgentPredict)
	mux.HandleFunc("POST /api/agents/summary", s.handleAgentSummary)
	mux.HandleFunc("GET /api/webhooks/events", s.handleListWebhookEvents)
	mux.HandleFunc("POST /api/webhooks/subscriptions", s.handleCreateWebhookSubscription)
	mux.HandleFunc("GET /api/webhooks/subscriptions", s.handleListWebhookSubscriptions)
	mux.HandleFunc("DELETE /api/webhooks/subscriptions/{id}", s.handleDeleteWebhookSubscription)
	mux.HandleFunc("POST /api/webhooks/subscriptions/{id}/active", s.handleSetWebhookSubscriptionActive)
	mux.HandleFunc("POST /api/webhooks/subscriptions/{id}/test", s.handleTestWebhookSubscription)
	mux.HandleFunc("GET /api/webhooks/subscriptions/{id}/logs", s.handleWebhookSubscriptionLogs)
	mux.HandleFunc("GET /api/webhooks/dashboard", s.handleWebhookDashboard)
	mux.HandleFunc("GET /.well-known/ai-services.json", s.handleAIServicesWellKnown)
	mux.HandleFunc("GET /.well-known/x402.json", s.handleX402WellKnown)
	mux.HandleFunc("GET /llms.txt", s.handleLLMSTxt)
	mux.HandleFunc("GET /robots.txt", s.handleRobotsTxt)
	mux.HandleFunc("GET /sitemap.xml", s.handleSitemap)
	mux.HandleFunc("GET /marketplace/apis", s.handleMarketplaceAPIs)
	mux.HandleFunc("GET /marketplace/apis/{id}", s.handleMarketplaceAPI)
	mux.HandleFunc("GET /marketplace/capabilities", s.handleMarketplaceCapabilities)
	mux.HandleFunc("GET /marketplace/capabilities/{id}", s.handleMarketplaceCapability)
	mux.HandleFunc("GET /marketplace/capabilities/{id}/contract", s.handleMarketplaceCapabilityContract)
	mux.HandleFunc("POST /marketplace/capabilities/{id}/purchase", s.handleMarketplaceCapabilityPurchase)
	mux.HandleFunc("POST /marketplace/capabilities/{id}/usage", s.handleMarketplaceCapabilityUsage)
	mux.HandleFunc("GET /marketplace/products", s.handleMarketplaceProducts)
	mux.HandleFunc("GET /marketplace/products/{id}", s.handleMarketplaceProduct)
	mux.HandleFunc("POST /marketplace/purchase", s.handleMarketplacePurchaseCreate)
	mux.HandleFunc("GET /marketplace/purchase/{id}", s.handleMarketplacePurchaseGet)
	mux.HandleFunc("POST /marketplace/purchase/{id}/execute", s.handleMarketplacePurchaseExecute)
	mux.HandleFunc("POST /marketplace/usage", s.handleMarketplaceUsage)
	mux.HandleFunc("POST /v1/access/quote", s.handleAccessQuote)
	mux.HandleFunc("POST /v1/access/purchase", s.handleAccessPurchase)
	mux.HandleFunc("GET /v1/access/{id}", s.handleAccessGet)
	mux.HandleFunc("POST /v1/meter/usage", s.handleMeterUsage)
	mux.HandleFunc("GET /agent/v1/capabilities", s.handleAgentCapabilities)
	mux.HandleFunc("POST /agent/connect", s.handleAgentConnect)
	mux.HandleFunc("GET /agent/v1/capabilities/{capability}/contract", s.handleAgentCapabilityContract)
	mux.HandleFunc("POST /agent/v1/capabilities/{capability}/route", s.handleAgentCapabilityRoute)
	mux.HandleFunc("POST /agent/v1/capabilities/{capability}/execute", s.handleAgentCapabilityExecute)
	mux.HandleFunc("GET /agent/v1/assets", s.handleAgentAssets)
	mux.HandleFunc("POST /agent/v1/trade/quote", s.handleAgentTradeQuote)
	mux.HandleFunc("POST /agent/v1/trade/execute", s.handleAgentTradeExecute)
	mux.HandleFunc("GET /agent/v1/trade/{id}", s.handleAgentTradeGet)
	mux.HandleFunc("GET /openapi.json", s.handleOpenAPI)
	mux.HandleFunc("GET /rates", s.handleChainFXRates)
	mux.HandleFunc("POST /quote", s.handleChainFXQuote)
	mux.HandleFunc("POST /buy", s.handleChainFXBuy)
	mux.HandleFunc("POST /sell", s.handleChainFXSell)
	mux.HandleFunc("GET /order/{id}", s.handleChainFXOrder)
	mux.HandleFunc("POST /webhooks/test", s.handleChainFXWebhookTest)
	mux.HandleFunc("POST /webhooks/retry", s.handleChainFXWebhookRetry)
	mux.HandleFunc("GET /api/price", s.handlePrice)
	mux.HandleFunc("GET /api/quote", s.handleQuote)
	mux.HandleFunc("POST /api/quote", s.handleQuote)
	mux.HandleFunc("POST /api/buy", s.handleCreateBuy)
	mux.HandleFunc("GET /api/buy/{id}", s.handleGetBuy)
	mux.HandleFunc("GET /api/buy/{id}/stream", s.handleBuyStream)
	mux.HandleFunc("POST /api/order", s.handleCreateOrder)
	mux.HandleFunc("GET /api/order/{id}", s.handleGetOrder)
	mux.HandleFunc("GET /api/order/{id}/stream", s.handleOrderStream)
	mux.HandleFunc("POST /api/order/{id}/deposit", s.handleDeposit)
	mux.HandleFunc("POST /api/order/{id}/payout", s.handlePayout)
	mux.HandleFunc("POST /api/pix/webhook", s.handlePixWebhook)
	mux.HandleFunc("POST /api/pix/webhook/buy", s.handlePixWebhookBuy)
	mux.HandleFunc("POST /api/stripe/webhook/buy", s.handleStripeWebhookBuy)
	mux.HandleFunc("POST /internal/sweep", s.handleInternalSweep)
	mux.HandleFunc("POST /internal/email/test", s.handleEmailTest)
	mux.HandleFunc("POST /internal/email/marketing", s.handleMarketingEmail)
	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, _ *http.Request) { writeJSON(w, http.StatusOK, map[string]any{"ok": true}) })
	mux.HandleFunc("GET /readyz", s.handleReady)
	return securityHeaders(cors(s.cfg, withRequestID(s.withDeveloperRequestLog(s.withPublicSurfaceGuards(s.withSmartRateLimit(mux))))))
}
